name: CICD for Youtube

on:
  push:
    branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use node js
        uses: actions/setup-node@v1
        with:
         node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm install
          npm run build

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: /home/runner/work/githubcicddeployec2onlybuilddist/githubcicddeployec2onlybuilddist/ # or path/to/artifact

        env: 
          CI: true   


  depoly:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
     - name: SSH deploy
       uses: appleboy/ssh-action@master
       with:
          host: ${{ secrets.HOST }}
          username:  ${{ secrets.USER }}
          key:  ${{ secrets.KEY }}
          port:  ${{ secrets.PORT }}
      #  - name: copy file via ssh password
      #    uses: appleboy/scp-action@master
      #    with:
      #       host: ${{ secrets.HOST }}
      #       username: ${{ secrets.USER }}
      #       password: ${{ secrets.KEY }}
      #       port: ${{ secrets.PORT }}
      #       source: my-artifact
      #       target: "test"
          script: |
              curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
              . ~/.nvm/nvm.sh

               nvm instal 14
               npm install -g pm2
               cd ~/CICD
               git pull origin main
               npm install
               npm run build
               pm2 restart api
       
    #  - name: Download Artifact from build    
    #    uses: actions/download-artifact@v3
    #    with:
    #       name: my-artifact




